name: Notify n8n on release & update version

on:
  release:
    types: [published]

jobs:
  release-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # push dans la branche de PR
      pull-requests: write     # créer + auto-merge la PR

    steps:
    # 1. checkout complet
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. retrouver le tag précédent (inchangé)
    - id: get_previous_tag
      run: |
        previous=$(git describe --tags --abbrev=0 ${{ github.event.release.tag_name }}^ 2>/dev/null || echo "")
        echo "previous_tag=$previous" >> $GITHUB_OUTPUT

    # 3. liste des commits (inchangé)
    - id: get_commits
      run: |
        new="${{ github.event.release.tag_name }}"
        old="${{ steps.get_previous_tag.outputs.previous_tag }}"
        if [ -z "$old" ]; then
          list=$(git log $new --pretty=format:"- %s (%h)")
        else
          list=$(git log $old..$new --pretty=format:"- %s (%h)")
        fi
        echo "commits<<EOF" >> $GITHUB_OUTPUT
        echo "$list" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    # 4. bump de version dans settings_schema.json
    - name: Bump theme_version
      run: |
        ver=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
        jq --arg v "$ver" 'map(if .name=="theme_info" then .theme_version=$v else . end)' \
           config/settings_schema.json > tmp && mv tmp config/settings_schema.json

    # 5. créer une PR signée + activer l’auto-merge squash
    - name: Create PR
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.PERSONAL_GH_TOKEN }}   # PAT repo/* ou fine-grained
        branch: release-bot/${{ github.run_id }}
        commit-message: |
          chore: bump theme version to ${{ github.event.release.tag_name }}
        title: "chore: bump theme version to ${{ github.event.release.tag_name }}"
        body: "Automated release bump."
        sign-commits: true                        # commit « Verified » ✔

    - name: Enable PR automerge (squash)
      if: steps.cpr.outputs.pull-request-operation == 'created'
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: ${{ secrets.PERSONAL_GH_TOKEN }}
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
        merge-method: squash                      # linéarité respectée

    # 6. notifier n8n – exactement comme avant
    - name: Send to n8n webhook
      env:
        TAG: ${{ github.event.release.tag_name }}
        BODY: ${{ github.event.release.body }}
        COMMITS: ${{ steps.get_commits.outputs.commits }}
        URL: ${{ secrets.N8N_RELEASE_WEBHOOK }}
      run: |
        payload=$(jq -n --arg tag "$TAG" --arg body "$BODY" \
                     --arg commits "$COMMITS" \
                     '{tag:$tag,release_notes:$body,commits:$commits}')
        curl -X POST -H "Content-Type: application/json" -d "$payload" "$URL"
